### ISSUE TITLE
Load position problem at the silos.

### ISSUE THREAD

**Issue by Roby1164** [Stephan-S/FS25_AutoDrive#15] opened 2024-12-26 16:50 UTC
Load position problem at the silos.
The vehicle stops before reaching the correct position, to load the trailer, it seems that it calculates the nose of the tractor and not the trailer.
I tried in various ways, modifying the track, target point, but nothing to do. See photo
![Screenshot_16](https://github.com/user-attachments/assets/9b930f9f-9170-477f-bace-b4b8d20238e1)

**Comment by Iwan1803** [comment] 2024-12-27 00:01
Is this a vanilla silo or barn or a mod?

**Comment by Roby1164** [comment] 2024-12-27 07:49
> Is this a vanilla silo or barn or a mod?

This is a mod, but today I have to do some more tests, since yesterday evening, with another trailer, also a mod, it unloaded and loaded regularly. I have the impression that it is related to the type of trailer, the one that worked unloads only from the back, while this little green one, original trailer, can unload also laterally. I will do some more tests and I will update you.

**Comment by Roby1164** [comment] 2024-12-27 10:53
I made a video, to try to show you what happens, I activated the debug, and did various tests, where as you can see, with a tractor (original) it always gets stuck in that position, while with the other, sometimes it works sometimes not, and finally I did a loading and unloading on the other silo, which are then identical, only the product changes, and as you can see in that one there are no problems. I also attach the log, and I add that, by activating the debug, then the game gets stuck in the closing phase, another problem, which however does not compromise the regular functioning. https://drive.google.com/file/d/17hFefIBV_XGryofZ3WAGXdt0Atm3dILX/view?usp=sharing

**Comment by ThomasMatern** [comment] 2024-12-28 06:35
@Roby1164 the link requires me to request access. Please make the video publicly accessible.

**Comment by floggydev** [comment] 2024-12-29 07:08
I came across a similar but maybe not the same issue (I am not sure).
It happens to me with FED Mods Multisilo 4000. The tractor stands in front of the passing through and does not move any further. As soon as I deactivate the collision detection the tractor starts moving and after hitting the tricker the unloading process starts. It look like that auto drive is afraid of a possible collision although the route has enough space for the passing through.

**Comment by Roby1164** [comment] 2024-12-29 07:36
> @Roby1164 the link requires me to request access. Please make the video publicly accessible.

it is shared with everyone, but lately google drive, has some problems, since they changed the rules and some parameters.
Retry

**Comment by Roby1164** [comment] 2024-12-29 07:40
After further tests, I found that the problem only occurs with some vehicles combined with some trailers, now I'm using another tractor with the same trailers and it seems to work.... I don't understand where the problem is, perhaps as floggydev said, it could be related to the collision detection, which on some vehicles gives problems...

**Comment by floggydev** [comment] 2024-12-29 07:43
I am using Fendt 1050 and Fendt Tigo 75 VR D both vanilla.

**Comment by Farmer4liife** [comment] 2024-12-30 03:29
i was having the same problem with multiple vehicles and found a work around by turning off collision detection in the settings menu.

**Comment by Iwan1803** [comment] 2024-12-30 07:53
One problem is, that some modders seem to use wrong/outdated collision bits and therefore AD stops in front of the triggers. That's not an AD problem and the modders have to fix it.

If a Vanilla vehicle combination has a problem with a Vanilla silo, then please comment the whole vehicle combination here so that we check it: front weight, tractor, wheels with weights, trailer, etc.

**Comment by floggydev** [comment] 2024-12-30 08:58
Thanks for clarification, @Iwan1803.

**Comment by Roby1164** [comment] 2024-12-30 11:19
> One problem is, that some modders seem to use wrong/outdated collision bits and therefore AD stops in front of the triggers. That's not an AD problem and the modders have to fix it.
> 
> If a Vanilla vehicle combination has a problem with a Vanilla silo, then please comment the whole vehicle combination here so that we check it: front weight, tractor, wheels with weights, trailer, etc.

I don't think the problem is with the silo mod, but with the vehicle collision zone, which I don't know if it's for AD or the Giants one, in fact some vehicles and trailers have the problem while others don't, and then it's also random, sometimes they pass and do the job, while sometimes the same vehicle/trailer gets stuck. It seems like it's the pavement, the possible small difference in height. However, if we remove the collision detection from AD, which I still haven't understood if with that NO, it switches to a Giants collision detection or is deactivated completely, the problem disappears.
As soon as I can, I'll try to do a test with a vanilla silo...

**Comment by Iwan1803** [comment] 2024-12-30 11:41
Trust me: there are silo mods with wrong collision bits 😉
Also AD doesn't generate collision boxes by itselfe but uses the one from the vehicles.
If the same vehicle can drive to the trigger and sometimes not, then it maybe could be a problem of new terra forming from Giants. This also causes sometimes that waypoints slide into the ground or float in the air during creation. It's really strange...
Next time if a vehicle stops in front of the silo then try to change the collision height detection. Standard should be 0.5.

One last hint: if you hover with the mouse cursor over an AD option, a help text should appear next to it....

**Comment by Roby1164** [comment] 2024-12-30 16:32
> Trust me: there are silo mods with wrong collision bits 😉 Also AD doesn't generate collision boxes by itselfe but uses the one from the vehicles. If the same vehicle can drive to the trigger and sometimes not, then it maybe could be a problem of new terra forming from Giants. This also causes sometimes that waypoints slide into the ground or float in the air during creation. It's really strange... Next time if a vehicle stops in front of the silo then try to change the collision height detection. Standard should be 0.5.
> 
> One last hint: if you hover with the mouse cursor over an AD option, a help text should appear next to it....

Look here, if it can help you understand the problem.
![Screenshot_32](https://github.com/user-attachments/assets/0175150f-f25d-49fc-ad61-a68189025165)

**Comment by ThomasMatern** [comment] 2024-12-30 20:31
@Roby1164 please reproduce the issue with a vanilla tractor, vanilla trailer and a vanilla silo. 
Also, you still have not told us what kind of modded silo this is, so there is nothing we can do at this point.

**Comment by ThomasMatern** [comment] 2024-12-30 23:14
Also, this might be related (and fixed by) #53

**Comment by Roby1164** [comment] 2024-12-31 08:02
> @Roby1164 please reproduce the issue with a vanilla tractor, vanilla trailer and a vanilla silo. Also, you still have not told us what kind of modded silo this is, so there is nothing we can do at this point.

The tractor and trailer are vanilla, while the silo is a mod, but nothing special, it is a drying silo, you put the grass and unload the hay, it has the same parameters as the vanilla silos. But there is a fact that leaves me perplexed, the strange fact is that, if it were a collision problem, it should be easier for the large trailer to have it, and not the small one, instead here the opposite happens, and it is always the small one that has the problem, a problem that I have partially solved, by slightly moving the path outwards (to the left in this case) in this way the problem does not arise, and the trailer proceeds and unloads/loads without problems. in this way, however, the small trailer, unloads laterally, since it has this possibility, while the large trailers, which unload only from the back, have difficulty unloading. and often stop not finding the unloading trigger. Today I will try with that modification you made, to see if it solves the problem.

**Comment by ThomasMatern** [comment] 2024-12-31 10:11
Closing the ticket because the reporter is unwilling to share basic information we requested

**Closed by ThomasMatern** 2024-12-31 10:11 UTC
Labels: Wait for user/feedback
